<?php
//
// File generated by Dolibarr installer 11.0.0 on 11 Fév. 2020
//
// Take a look at conf.php.example file for an example of conf.php file
// and explanations for all possibles parameters.
//
#$dolibarr_main_url_root='http://newgestionbio-timc.imag.fr';
$dolibarr_main_url_root='https://gestion-tree.timc.fr';
$dolibarr_main_document_root='/var/www/gestion-bio/htdocs';
$dolibarr_main_url_root_alt='/custom';
$dolibarr_main_document_root_alt='/var/www/gestion-bio/htdocs/custom';
$dolibarr_main_data_root='/var/www/gestion-bio/documents';
$dolibarr_main_db_host='localhost';
$dolibarr_main_db_port='3306';
$dolibarr_main_db_name='dolibarr';
$dolibarr_main_db_prefix='llx_';
$dolibarr_main_db_user='dolibarr_user';
$dolibarr_main_db_pass='crypted:VUF9enNyg4NDQUJKMg==';
$dolibarr_main_db_type='mysqli';
$dolibarr_main_db_character_set='latin1';
$dolibarr_main_db_collation='latin1_swedish_ci';
// Authentication settings
// Rajouter ",dolibarr" pour autoriser l'accès avec compte local
$dolibarr_main_authentication='ldap';

//$dolibarr_main_demo='autologin,autopass';
// Security settings
$dolibarr_main_prod='1';
$dolibarr_main_force_https='0';
$dolibarr_main_restrict_os_commands='mysqldump, mysql, pg_dump, pgrestore';
$dolibarr_nocsrfcheck='0';
$dolibarr_main_instance_unique_id='906bee3fbe1d7d5e263531205352cda5';
$dolibarr_mailing_limit_sendbyweb='0';


$dolibarr_main_auth_ldap_host = 'timc-ldap.imag.fr';
$dolibarr_main_auth_ldap_port = '389';
$dolibarr_main_auth_ldap_version = '3';
$dolibarr_main_auth_ldap_servertype = 'activedirectory';
//$dolibarr_main_auth_ldap_login_attribute = 'samaccountname';
$dolibarr_main_auth_ldap_login_attribute = 'cn';
$dolibarr_main_auth_ldap_dn = 'dc=timc,dc=fr';
$dolibarr_main_auth_ldap_admin_login = 'cn=readldap,cn=users,dc=timc,dc=fr';
$dolibarr_main_auth_ldap_admin_pass = 'A:ot3peoD';
//$dolibarr_main_auth_ldap_filter = '&(objectClass=user)(objectCategory=person)(!(userAccountControl:1.2.840.113556.1.4.803:=2))';
$dolibarr_main_auth_ldap_debug = 'false';

//$dolibarr_lib_FPDF_PATH='';
//$dolibarr_lib_TCPDF_PATH='';
//$dolibarr_lib_FPDI_PATH='';
//$dolibarr_lib_TCPDI_PATH='';
//$dolibarr_lib_ADODB_PATH='';
//$dolibarr_lib_GEOIP_PATH='';
//$dolibarr_lib_NUSOAP_PATH='';
//$dolibarr_lib_PHPEXCEL_PATH='';
//$dolibarr_lib_ODTPHP_PATH='';
//$dolibarr_lib_ODTPHP_PATHTOPCLZIP='';
//$dolibarr_js_CKEDITOR='';
//$dolibarr_js_JQUERY='';
//$dolibarr_js_JQUERY_UI='';
//$dolibarr_js_JQUERY_FLOT='';

//$dolibarr_font_DOL_DEFAULT_TTF='';
//$dolibarr_font_DOL_DEFAULT_TTF_BOLD='';
